default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>
  host: localhost
  password: <%= ENV.fetch("DB_PASSWORD") { 'p@ssw0rd' } %>
  timeout: 5000

development:
  <<: *default
  database: starwars-dev
  host: <%= ENV.fetch("DB_HOST") { 'localhost' } %>
  user: <%= ENV.fetch("DB_USER") { 'postgres' } %>

test:
  <<: *default
  database: starwars-test
  host: <%= ENV.fetch("DB_HOST") { 'localhost' } %>
  user: <%= ENV.fetch("DB_USER") { 'postgres' } %>

production:
  <<: *default
  database: <%= ENV.fetch("DB_DATABASE") { 'starwars-dev' } %>
  host: <%= ENV.fetch("DB_HOST") { 'localhost' } %>
  user: <%= ENV.fetch("DB_USER") { 'xpto' } %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>
  password: <%= ENV.fetch("DB_PASSWORD") { 'xpto' } %>
